export const theme = {
  colors: {
    white: '#FFFFFF',
    flashWhite: '#F3F3F8',
    gainsboro: '#DBDBE8',
    black: '#000000',
    primary: '#16162E',
    purple: '#8445EE',
    orange: '#F2B01E',
    independence: '#505070',
  },
  fonts: {
    primary: '"Montserrat", sans-serif',
    secondary: '"DM Serif Display", serif',
  },
  fontSizes: {
    small: '15px',
    regular: '16px',
    medium: '18px',
    large: '20px',
    xLarge: '65px',
    xxLarge: '80px',
  },
  fontWeights: {
    thin: 100,
    extraLight: 200,
    light: 300,
    regular: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
    black: 900,
  },
  borderRadius: {
    small: '2px',
    regular: '5px',
    medium: '8px',
    large: '15px',
    xLarge: '20px',
    xxLarge: '25px',
    circle: '50%',
  },
  animations: {
    easeInOut: 'all 0.2s ease-in-out',
    easeInfinite: '5s ease infinite',
    linearInfinite: '1s linear infinite',
  },
}
