export const theme = {
  colors: {
    white: '#FFFFFF',
    flashWhite: '#F3F3F8',
    black: '#000000',
    darkGunmetal: '#16162E',
    purple: '#8445EE',
  },
  fonts: {
    primary: '"Montserrat", sans-serif',
    secondary: '"DM Serif Display", serif',
  },
  fontSizes: {
    small: '12px',
    regular: '14px',
    medium: '17.5px',
    large: '20px',
    xLarge: '24px',
    xxLarge: '32px',
  },
  fontWeights: {
    thin: 100,
    extraLight: 200,
    light: 300,
    regular: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
    black: 900,
  },
  borderRadius: {
    small: '2px',
    regular: '5px',
    medium: '10px',
    large: '15px',
    xLarge: '20px',
    xxLarge: '25px',
    circle: '50%',
  },
  animations: {
    easeInfinite: '5s ease infinite',
    easeInOut: 'all 0.2s ease-in-out',
  },
}
